/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppRecurringIndexRouteImport } from './routes/_app/recurring/index'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppCreditNotesIndexRouteImport } from './routes/_app/credit-notes/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppAgreementsIndexRouteImport } from './routes/_app/agreements/index'
import { Route as QTokenLogoRouteImport } from './routes/q.$token_.logo'
import { Route as PayTokenPdfRouteImport } from './routes/pay.$token_.pdf'
import { Route as PayTokenLogoRouteImport } from './routes/pay.$token_.logo'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiPaymentsStripeWebhookRouteImport } from './routes/api/payments/stripe-webhook'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'
import { Route as ApiCronMarkOverdueRouteImport } from './routes/api/cron/mark-overdue'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ATokenPdfRouteImport } from './routes/a.$token_.pdf'
import { Route as ATokenLogoRouteImport } from './routes/a.$token_.logo'
import { Route as AppRecurringScheduleIdRouteImport } from './routes/_app/recurring/$scheduleId'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app/quotes/$quoteId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppCreditNotesCreditNoteIdRouteImport } from './routes/_app/credit-notes/$creditNoteId'
import { Route as AppContactsNewRouteImport } from './routes/_app/contacts/new'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts/$contactId'
import { Route as AppAgreementsNewRouteImport } from './routes/_app/agreements/new'
import { Route as AppAgreementsAgreementIdRouteImport } from './routes/_app/agreements/$agreementId'
import { Route as AppApprovalsApprovalIdPreviewDotpdfRouteImport } from './routes/app.approvals.$approvalId.preview[.]pdf'
import { Route as ApiAgreementsAgreementIdPdfRouteImport } from './routes/api/agreements/$agreementId.pdf'
import { Route as AppAgreementsAgreementIdEditRouteImport } from './routes/_app/agreements/$agreementId_.edit'
import { Route as ApiDocumentsKindDocumentIdPdfRouteImport } from './routes/api/documents/$kind/$documentId.pdf'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringIndexRoute = AppRecurringIndexRouteImport.update({
  id: '/recurring/',
  path: '/recurring/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditNotesIndexRoute = AppCreditNotesIndexRouteImport.update({
  id: '/credit-notes/',
  path: '/credit-notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementsIndexRoute = AppAgreementsIndexRouteImport.update({
  id: '/agreements/',
  path: '/agreements/',
  getParentRoute: () => AppRoute,
} as any)
const QTokenLogoRoute = QTokenLogoRouteImport.update({
  id: '/q/$token_/logo',
  path: '/q/$token/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenPdfRoute = PayTokenPdfRouteImport.update({
  id: '/pay/$token_/pdf',
  path: '/pay/$token/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenLogoRoute = PayTokenLogoRouteImport.update({
  id: '/pay/$token_/logo',
  path: '/pay/$token/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsStripeWebhookRoute =
  ApiPaymentsStripeWebhookRouteImport.update({
    id: '/api/payments/stripe-webhook',
    path: '/api/payments/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMarkOverdueRoute = ApiCronMarkOverdueRouteImport.update({
  id: '/api/cron/mark-overdue',
  path: '/api/cron/mark-overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenPdfRoute = ATokenPdfRouteImport.update({
  id: '/a/$token_/pdf',
  path: '/a/$token/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenLogoRoute = ATokenLogoRouteImport.update({
  id: '/a/$token_/logo',
  path: '/a/$token/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecurringScheduleIdRoute = AppRecurringScheduleIdRouteImport.update({
  id: '/recurring/$scheduleId',
  path: '/recurring/$scheduleId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditNotesCreditNoteIdRoute =
  AppCreditNotesCreditNoteIdRouteImport.update({
    id: '/credit-notes/$creditNoteId',
    path: '/credit-notes/$creditNoteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppContactsNewRoute = AppContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementsNewRoute = AppAgreementsNewRouteImport.update({
  id: '/agreements/new',
  path: '/agreements/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementsAgreementIdRoute =
  AppAgreementsAgreementIdRouteImport.update({
    id: '/agreements/$agreementId',
    path: '/agreements/$agreementId',
    getParentRoute: () => AppRoute,
  } as any)
const AppApprovalsApprovalIdPreviewDotpdfRoute =
  AppApprovalsApprovalIdPreviewDotpdfRouteImport.update({
    id: '/app/approvals/$approvalId/preview.pdf',
    path: '/app/approvals/$approvalId/preview.pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgreementsAgreementIdPdfRoute =
  ApiAgreementsAgreementIdPdfRouteImport.update({
    id: '/api/agreements/$agreementId/pdf',
    path: '/api/agreements/$agreementId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgreementsAgreementIdEditRoute =
  AppAgreementsAgreementIdEditRouteImport.update({
    id: '/agreements/$agreementId_/edit',
    path: '/agreements/$agreementId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const ApiDocumentsKindDocumentIdPdfRoute =
  ApiDocumentsKindDocumentIdPdfRouteImport.update({
    id: '/api/documents/$kind/$documentId/pdf',
    path: '/api/documents/$kind/$documentId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/billing': typeof AppBillingRoute
  '/catalog': typeof AppCatalogRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/agreements/$agreementId': typeof AppAgreementsAgreementIdRoute
  '/agreements/new': typeof AppAgreementsNewRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/credit-notes/$creditNoteId': typeof AppCreditNotesCreditNoteIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/recurring/$scheduleId': typeof AppRecurringScheduleIdRoute
  '/a/$token/logo': typeof ATokenLogoRoute
  '/a/$token/pdf': typeof ATokenPdfRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/pay/$token/logo': typeof PayTokenLogoRoute
  '/pay/$token/pdf': typeof PayTokenPdfRoute
  '/q/$token/logo': typeof QTokenLogoRoute
  '/agreements/': typeof AppAgreementsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/credit-notes/': typeof AppCreditNotesIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/recurring/': typeof AppRecurringIndexRoute
  '/agreements/$agreementId/edit': typeof AppAgreementsAgreementIdEditRoute
  '/api/agreements/$agreementId/pdf': typeof ApiAgreementsAgreementIdPdfRoute
  '/app/approvals/$approvalId/preview.pdf': typeof AppApprovalsApprovalIdPreviewDotpdfRoute
  '/api/documents/$kind/$documentId/pdf': typeof ApiDocumentsKindDocumentIdPdfRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/billing': typeof AppBillingRoute
  '/catalog': typeof AppCatalogRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/': typeof AppIndexRoute
  '/agreements/$agreementId': typeof AppAgreementsAgreementIdRoute
  '/agreements/new': typeof AppAgreementsNewRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/credit-notes/$creditNoteId': typeof AppCreditNotesCreditNoteIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/recurring/$scheduleId': typeof AppRecurringScheduleIdRoute
  '/a/$token/logo': typeof ATokenLogoRoute
  '/a/$token/pdf': typeof ATokenPdfRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/pay/$token/logo': typeof PayTokenLogoRoute
  '/pay/$token/pdf': typeof PayTokenPdfRoute
  '/q/$token/logo': typeof QTokenLogoRoute
  '/agreements': typeof AppAgreementsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/credit-notes': typeof AppCreditNotesIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/recurring': typeof AppRecurringIndexRoute
  '/agreements/$agreementId/edit': typeof AppAgreementsAgreementIdEditRoute
  '/api/agreements/$agreementId/pdf': typeof ApiAgreementsAgreementIdPdfRoute
  '/app/approvals/$approvalId/preview.pdf': typeof AppApprovalsApprovalIdPreviewDotpdfRoute
  '/api/documents/$kind/$documentId/pdf': typeof ApiDocumentsKindDocumentIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/pay/$token': typeof PayTokenRoute
  '/q/$token': typeof QTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agreements/$agreementId': typeof AppAgreementsAgreementIdRoute
  '/_app/agreements/new': typeof AppAgreementsNewRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/contacts/new': typeof AppContactsNewRoute
  '/_app/credit-notes/$creditNoteId': typeof AppCreditNotesCreditNoteIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/_app/recurring/$scheduleId': typeof AppRecurringScheduleIdRoute
  '/a/$token_/logo': typeof ATokenLogoRoute
  '/a/$token_/pdf': typeof ATokenPdfRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/mark-overdue': typeof ApiCronMarkOverdueRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/payments/stripe-webhook': typeof ApiPaymentsStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/pay/$token_/logo': typeof PayTokenLogoRoute
  '/pay/$token_/pdf': typeof PayTokenPdfRoute
  '/q/$token_/logo': typeof QTokenLogoRoute
  '/_app/agreements/': typeof AppAgreementsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/credit-notes/': typeof AppCreditNotesIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/recurring/': typeof AppRecurringIndexRoute
  '/_app/agreements/$agreementId_/edit': typeof AppAgreementsAgreementIdEditRoute
  '/api/agreements/$agreementId/pdf': typeof ApiAgreementsAgreementIdPdfRoute
  '/app/approvals/$approvalId/preview.pdf': typeof AppApprovalsApprovalIdPreviewDotpdfRoute
  '/api/documents/$kind/$documentId/pdf': typeof ApiDocumentsKindDocumentIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/activity'
    | '/approvals'
    | '/billing'
    | '/catalog'
    | '/onboarding'
    | '/settings'
    | '/a/$token'
    | '/accept-invitation/$invitationId'
    | '/api/mcp'
    | '/pay/$token'
    | '/q/$token'
    | '/agreements/$agreementId'
    | '/agreements/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/credit-notes/$creditNoteId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/recurring/$scheduleId'
    | '/a/$token/logo'
    | '/a/$token/pdf'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/cron/tick'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/pay/$token/logo'
    | '/pay/$token/pdf'
    | '/q/$token/logo'
    | '/agreements/'
    | '/contacts/'
    | '/credit-notes/'
    | '/invoices/'
    | '/quotes/'
    | '/recurring/'
    | '/agreements/$agreementId/edit'
    | '/api/agreements/$agreementId/pdf'
    | '/app/approvals/$approvalId/preview.pdf'
    | '/api/documents/$kind/$documentId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/activity'
    | '/approvals'
    | '/billing'
    | '/catalog'
    | '/onboarding'
    | '/settings'
    | '/a/$token'
    | '/accept-invitation/$invitationId'
    | '/api/mcp'
    | '/pay/$token'
    | '/q/$token'
    | '/'
    | '/agreements/$agreementId'
    | '/agreements/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/credit-notes/$creditNoteId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/recurring/$scheduleId'
    | '/a/$token/logo'
    | '/a/$token/pdf'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/cron/tick'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/pay/$token/logo'
    | '/pay/$token/pdf'
    | '/q/$token/logo'
    | '/agreements'
    | '/contacts'
    | '/credit-notes'
    | '/invoices'
    | '/quotes'
    | '/recurring'
    | '/agreements/$agreementId/edit'
    | '/api/agreements/$agreementId/pdf'
    | '/app/approvals/$approvalId/preview.pdf'
    | '/api/documents/$kind/$documentId/pdf'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/_app/activity'
    | '/_app/approvals'
    | '/_app/billing'
    | '/_app/catalog'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/a/$token'
    | '/accept-invitation/$invitationId'
    | '/api/mcp'
    | '/pay/$token'
    | '/q/$token'
    | '/_app/'
    | '/_app/agreements/$agreementId'
    | '/_app/agreements/new'
    | '/_app/contacts/$contactId'
    | '/_app/contacts/new'
    | '/_app/credit-notes/$creditNoteId'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/quotes/$quoteId'
    | '/_app/quotes/new'
    | '/_app/recurring/$scheduleId'
    | '/a/$token_/logo'
    | '/a/$token_/pdf'
    | '/api/auth/$'
    | '/api/cron/mark-overdue'
    | '/api/cron/tick'
    | '/api/payments/stripe-webhook'
    | '/api/trpc/$'
    | '/pay/$token_/logo'
    | '/pay/$token_/pdf'
    | '/q/$token_/logo'
    | '/_app/agreements/'
    | '/_app/contacts/'
    | '/_app/credit-notes/'
    | '/_app/invoices/'
    | '/_app/quotes/'
    | '/_app/recurring/'
    | '/_app/agreements/$agreementId_/edit'
    | '/api/agreements/$agreementId/pdf'
    | '/app/approvals/$approvalId/preview.pdf'
    | '/api/documents/$kind/$documentId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  ATokenRoute: typeof ATokenRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiMcpRoute: typeof ApiMcpRoute
  PayTokenRoute: typeof PayTokenRoute
  QTokenRoute: typeof QTokenRoute
  ATokenLogoRoute: typeof ATokenLogoRoute
  ATokenPdfRoute: typeof ATokenPdfRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMarkOverdueRoute: typeof ApiCronMarkOverdueRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiPaymentsStripeWebhookRoute: typeof ApiPaymentsStripeWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  PayTokenLogoRoute: typeof PayTokenLogoRoute
  PayTokenPdfRoute: typeof PayTokenPdfRoute
  QTokenLogoRoute: typeof QTokenLogoRoute
  ApiAgreementsAgreementIdPdfRoute: typeof ApiAgreementsAgreementIdPdfRoute
  AppApprovalsApprovalIdPreviewDotpdfRoute: typeof AppApprovalsApprovalIdPreviewDotpdfRoute
  ApiDocumentsKindDocumentIdPdfRoute: typeof ApiDocumentsKindDocumentIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring/': {
      id: '/_app/recurring/'
      path: '/recurring'
      fullPath: '/recurring/'
      preLoaderRoute: typeof AppRecurringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-notes/': {
      id: '/_app/credit-notes/'
      path: '/credit-notes'
      fullPath: '/credit-notes/'
      preLoaderRoute: typeof AppCreditNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agreements/': {
      id: '/_app/agreements/'
      path: '/agreements'
      fullPath: '/agreements/'
      preLoaderRoute: typeof AppAgreementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/q/$token_/logo': {
      id: '/q/$token_/logo'
      path: '/q/$token/logo'
      fullPath: '/q/$token/logo'
      preLoaderRoute: typeof QTokenLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token_/pdf': {
      id: '/pay/$token_/pdf'
      path: '/pay/$token/pdf'
      fullPath: '/pay/$token/pdf'
      preLoaderRoute: typeof PayTokenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token_/logo': {
      id: '/pay/$token_/logo'
      path: '/pay/$token/logo'
      fullPath: '/pay/$token/logo'
      preLoaderRoute: typeof PayTokenLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/stripe-webhook': {
      id: '/api/payments/stripe-webhook'
      path: '/api/payments/stripe-webhook'
      fullPath: '/api/payments/stripe-webhook'
      preLoaderRoute: typeof ApiPaymentsStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/mark-overdue': {
      id: '/api/cron/mark-overdue'
      path: '/api/cron/mark-overdue'
      fullPath: '/api/cron/mark-overdue'
      preLoaderRoute: typeof ApiCronMarkOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token_/pdf': {
      id: '/a/$token_/pdf'
      path: '/a/$token/pdf'
      fullPath: '/a/$token/pdf'
      preLoaderRoute: typeof ATokenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token_/logo': {
      id: '/a/$token_/logo'
      path: '/a/$token/logo'
      fullPath: '/a/$token/logo'
      preLoaderRoute: typeof ATokenLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recurring/$scheduleId': {
      id: '/_app/recurring/$scheduleId'
      path: '/recurring/$scheduleId'
      fullPath: '/recurring/$scheduleId'
      preLoaderRoute: typeof AppRecurringScheduleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-notes/$creditNoteId': {
      id: '/_app/credit-notes/$creditNoteId'
      path: '/credit-notes/$creditNoteId'
      fullPath: '/credit-notes/$creditNoteId'
      preLoaderRoute: typeof AppCreditNotesCreditNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/new': {
      id: '/_app/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AppContactsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agreements/new': {
      id: '/_app/agreements/new'
      path: '/agreements/new'
      fullPath: '/agreements/new'
      preLoaderRoute: typeof AppAgreementsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agreements/$agreementId': {
      id: '/_app/agreements/$agreementId'
      path: '/agreements/$agreementId'
      fullPath: '/agreements/$agreementId'
      preLoaderRoute: typeof AppAgreementsAgreementIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/$approvalId/preview.pdf': {
      id: '/app/approvals/$approvalId/preview.pdf'
      path: '/app/approvals/$approvalId/preview.pdf'
      fullPath: '/app/approvals/$approvalId/preview.pdf'
      preLoaderRoute: typeof AppApprovalsApprovalIdPreviewDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agreements/$agreementId/pdf': {
      id: '/api/agreements/$agreementId/pdf'
      path: '/api/agreements/$agreementId/pdf'
      fullPath: '/api/agreements/$agreementId/pdf'
      preLoaderRoute: typeof ApiAgreementsAgreementIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agreements/$agreementId_/edit': {
      id: '/_app/agreements/$agreementId_/edit'
      path: '/agreements/$agreementId/edit'
      fullPath: '/agreements/$agreementId/edit'
      preLoaderRoute: typeof AppAgreementsAgreementIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/documents/$kind/$documentId/pdf': {
      id: '/api/documents/$kind/$documentId/pdf'
      path: '/api/documents/$kind/$documentId/pdf'
      fullPath: '/api/documents/$kind/$documentId/pdf'
      preLoaderRoute: typeof ApiDocumentsKindDocumentIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgreementsAgreementIdRoute: typeof AppAgreementsAgreementIdRoute
  AppAgreementsNewRoute: typeof AppAgreementsNewRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppContactsNewRoute: typeof AppContactsNewRoute
  AppCreditNotesCreditNoteIdRoute: typeof AppCreditNotesCreditNoteIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppRecurringScheduleIdRoute: typeof AppRecurringScheduleIdRoute
  AppAgreementsIndexRoute: typeof AppAgreementsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppCreditNotesIndexRoute: typeof AppCreditNotesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppRecurringIndexRoute: typeof AppRecurringIndexRoute
  AppAgreementsAgreementIdEditRoute: typeof AppAgreementsAgreementIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgreementsAgreementIdRoute: AppAgreementsAgreementIdRoute,
  AppAgreementsNewRoute: AppAgreementsNewRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppContactsNewRoute: AppContactsNewRoute,
  AppCreditNotesCreditNoteIdRoute: AppCreditNotesCreditNoteIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppRecurringScheduleIdRoute: AppRecurringScheduleIdRoute,
  AppAgreementsIndexRoute: AppAgreementsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppCreditNotesIndexRoute: AppCreditNotesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppRecurringIndexRoute: AppRecurringIndexRoute,
  AppAgreementsAgreementIdEditRoute: AppAgreementsAgreementIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  ATokenRoute: ATokenRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiMcpRoute: ApiMcpRoute,
  PayTokenRoute: PayTokenRoute,
  QTokenRoute: QTokenRoute,
  ATokenLogoRoute: ATokenLogoRoute,
  ATokenPdfRoute: ATokenPdfRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMarkOverdueRoute: ApiCronMarkOverdueRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiPaymentsStripeWebhookRoute: ApiPaymentsStripeWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  PayTokenLogoRoute: PayTokenLogoRoute,
  PayTokenPdfRoute: PayTokenPdfRoute,
  QTokenLogoRoute: QTokenLogoRoute,
  ApiAgreementsAgreementIdPdfRoute: ApiAgreementsAgreementIdPdfRoute,
  AppApprovalsApprovalIdPreviewDotpdfRoute:
    AppApprovalsApprovalIdPreviewDotpdfRoute,
  ApiDocumentsKindDocumentIdPdfRoute: ApiDocumentsKindDocumentIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
